# language to use in travis containers
language: python
python:
  - "3.6" 
  - "3.7"  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
  
# command to run tests
script: 
  - pytest --cov --disable-warnings
sudo: required

after_success:
- coveralls
